// PRODUCTS
export const MARK_PRODUCT = "MARK_PRODUCT"
export const UNMARK_PRODUCT = "UNMARK_PRODUCT"

// CART
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART"

//USERS
export const ADD_USER = "ADD_USER"
export const REMOVE_USER = "REMOVE_USER"
